# Generated by Django 5.0.1 on 2024-01-03 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoricPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='имя продукта')),
                ('press', models.BigIntegerField(verbose_name='цена продукта')),
                ('county', models.CharField(choices=[('MOSCOW', 'MOSCOW'), ('UZBEKISTAN', 'UZBEKISTAN'), ('USA', 'USA')], max_length=50, verbose_name='страна')),
                ('config', models.BooleanField(verbose_name='я согласен')),
                ('category', models.CharField(choices=[('ТЕХНИКА', 'ТЕХНИКА'), ('БИЗНЕС', 'БИЗНЕС'), ('ЕДА', 'ЕДА'), ('МАШИНА', 'МАШИНА'), ('ДОМ', 'ДОМ')], max_length=50, verbose_name='категория продукта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
