# Generated by Django 5.0.1 on 2024-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usercategoricpublish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategoricpublish',
            name='press',
            field=models.CharField(max_length=50, verbose_name='цена продукта'),
        ),
    ]
