# Generated by Django 5.0.1 on 2024-01-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usercategoricpublish_press'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercategoricpublish',
            old_name='product',
            new_name='name',
        ),
    ]
