# Generated by Django 5.0.1 on 2024-01-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_product_usercategoricpublish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategoricpublish',
            name='config',
            field=models.BooleanField(null=True, verbose_name='я согласен'),
        ),
    ]
