# Generated by Django 5.0 on 2024-01-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usercategorypublishes_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategorypublishes',
            name='ofical',
            field=models.CharField(default=1, max_length=50, verbose_name='описание вашего продукта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BanUserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.CharField(choices=[('ПРОПАГАНДА', 'ПРОРАГАНДА'), ('ЗАПРЕШЁННЫЕ ВЕШИ', 'ЗАПРЕШЁННЫЕ ВЕШИ'), ('МНЕ СТАЛО НЕ ПРИЯТНО', 'МНЕ СТАЛО НЕ ПРИЯТНО'), ('НЕТУ ТАКОГО ТОВАРА ', 'НЕТУ ТАКОГО ТОВАРА'), ('НЕ КОРЕКТНОЕ ИМЯ', 'НЕ КОРЕКТНОЕ ИМЯ'), ('ПРОДАВЕЦ СЛИШКОМ ГРУБЫЙ', 'ПРОДАВЕЦ СЛИШКОМ ГРУБЫЙ')], max_length=50, verbose_name='выбирите причину жалаобы')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usercategorypublishes')),
            ],
        ),
    ]
