# Generated by Django 5.0 on 2024-01-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usercategorypublishes_ofical_banuserproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuserproduct',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usercategorypublishes'),
        ),
    ]
