# Generated by Django 5.0 on 2024-01-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banuserproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategorypublishes',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='название продукта'),
        ),
    ]
