# Generated by Django 5.0 on 2024-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usercategorypublishes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategorypublishes',
            name='one_photo',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
