# Generated by Django 5.0 on 2024-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userphoto_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userphoto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercategorypublishes',
            name='video',
            field=models.FileField(default=1, upload_to='vidio/'),
            preserve_default=False,
        ),
    ]
