# Generated by Django 5.0 on 2024-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_usercategorypublishes_video_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='master_card',
            field=models.IntegerField(default=1, verbose_name='номер от карты'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
