# Generated by Django 5.0 on 2024-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_userphoto_master_card_usercardinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardinput',
            name='type_card',
            field=models.CharField(choices=[('СБЕРБАНК', 'СБЕРБАНК'), ('UNIVERSALBANK', 'UNIVERSALBANK'), ('IPAKYULI', 'IPAKYULI'), ('INFIN BANK', 'INFIN BANK'), ('HUMO', 'HUMO'), ('XALKBANKI', 'XALKBANKI'), ('TINKOF', 'TINKOF')], default=1, max_length=50, verbose_name='назавание карты '),
            preserve_default=False,
        ),
    ]
