# Generated by Django 5.0 on 2024-01-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_usersocial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardinput',
            name='card',
            field=models.IntegerField(verbose_name='номер карты'),
        ),
    ]
