# Generated by Django 5.0 on 2024-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_usercardinput_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardinput',
            name='card',
            field=models.IntegerField(null=True, verbose_name='номер карты'),
        ),
    ]
